name: Deploy Diagnostic Scenarios Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: '$(System.DefaultWorkingDirectory)/_DiagnosticScenarios.Web'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Create Publish Directory
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Build Solution
      run: msbuild DiagnosticScenarios.Web.sln /p:Configuration=Release /p:Platform="Any CPU" /v:detailed

    - name: Publish Web App
      run: msbuild DiagnosticScenarios.Web/DiagnosticScenarios.Web.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:OutDir=${{ env.AZURE_WEBAPP_PACKAGE_PATH }} /v:detailed

    - name: List Published Files
      shell: pwsh
      run: |
        Get-ChildItem -Path ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -Recurse | Select-Object FullName

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./main.bicep
        parameters: |
          appServiceName=${{ env.AZURE_WEBAPP_NAME }}
          location=${{ secrets.AZURE_LOCATION }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 