name: Deploy - Missing Dependency App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add concurrency configuration to ensure only one workflow runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  APP_SERVICE_NAME: broken-webapp-aspnet-missingdependency-${{ github.actor }}
  APP_SERVICE_PLAN_NAME: broken-webapp-aspnet-common-${{ github.actor }}
  WEBAPP_URL: https://broken-webapp-aspnet-missingdependency-${{ github.actor }}.azurewebsites.net
  CONFIGURATION: 'Release'
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
  RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
  LOG_ANALYTICS_NAME: broken-webapp-aspnet-${{ github.actor }}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Restore NuGet Packages
      run: msbuild DiagnosticScenarios.sln /t:restore /p:RestorePackagesConfig=true
      
    - name: Publish to folder
      run: |
        Write-Host "Building solution..."
        msbuild DiagnosticScenarios.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Build /v:m /restore
        Write-Host "Publishing web project..."
        msbuild DiagnosticScenarios.Web\DiagnosticScenarios.Web.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="$env:GITHUB_WORKSPACE\published"
        Write-Host "Listing all files in published folder..."
        Get-ChildItem -Recurse -Path "$env:GITHUB_WORKSPACE\published"
        Write-Host "Removing required dependency..."
        Remove-Item -Path "$env:GITHUB_WORKSPACE\published\bin\*.dll" -Force -ErrorAction SilentlyContinue -Verbose
        Write-Host "Current directory: $(Get-Location)"
        Write-Host "Published directory contents:"
        Get-ChildItem -Path "$env:GITHUB_WORKSPACE\published" -Recurse | Select-Object FullName

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: ASP-app
        path: ./published
        if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
    - uses: actions/checkout@v4
  
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ASP-app
        
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.MANAGED_IDENTITY_CLIENTID }}
        tenant-id: ${{ secrets.TENANTID }}
        subscription-id: ${{ secrets.SUBSCRIPTIONID }}

    - name: Deploy Log Analytics Workspace
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./infra/loganalytics.bicep
        parameters: logAnalyticsName=${{ env.LOG_ANALYTICS_NAME }}
        deploymentName: loganalytics-missingdependency-${{ github.run_number }}

    - name: Deploy Bicep (Web App & App Service Plan)
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
        template: ./infra/missingdependency.bicep
        parameters: appServiceName=${{ env.APP_SERVICE_NAME }} appServicePlanName=${{ env.APP_SERVICE_PLAN_NAME }}
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: '${{ env.APP_SERVICE_NAME }}'
        slot-name: 'Production'
        package: ./

  test:
    runs-on: windows-latest
    needs: deploy
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: msbuild DiagnosticScenarios.sln /t:restore /p:RestorePackagesConfig=true

    - name: Build Solution in Release Mode
      run: |
        Write-Host "Building solution in Release mode..."
        msbuild DiagnosticScenarios.sln /p:Configuration=Release /p:Platform="Any CPU" /t:Build /v:m /restore /p:OutputPath="bin\Release"

    - name: Install NUnit Console Runner
      run: |
        Write-Host "Installing NUnit Console Runner..."
        nuget install NUnit.ConsoleRunner -Version 3.16.3 -OutputDirectory tools

    - name: Run Tests
      run: |
        Write-Host "Running tests..."
        $nunitPath = Join-Path $env:GITHUB_WORKSPACE "tools\NUnit.ConsoleRunner.3.16.3\tools\nunit3-console.exe"
        $testDll = Join-Path $env:GITHUB_WORKSPACE "DiagnosticScenarios.Tests\bin\Release\DiagnosticScenarios.Tests.dll"
        & $nunitPath $testDll --framework=net-4.8 --where "cat == MissingDependency"
      env:
        WEBAPP_URL: ${{ env.WEBAPP_URL }}
        RUN_SPECIALIZED_TESTS: MissingDependency 


