- name: Deploy Log Analytics Workspace
  uses: azure/arm-deploy@v1
  with:
    subscriptionId: ${{ env.SUBSCRIPTION_ID }}
    resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
    template: ./infra/loganalytics.bicep
    deploymentName: loganalytics-${{ github.workflow }}-${{ github.run_id }} 